In [ ]:
# One Hot Encoding

In [5]:
# import libraries 
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [6]:
#corpus
corpus = [['nlp'] , ['is'] , ['fun'] , ['amazing']]
# OneHotEncoder expects input as a 2D array

#create OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)

# fit and transform 
onehot = encoder.fit_transform(corpus)

In [7]:
print('Vocabulary:' , encoder.categories_)
print('One Hot Encoding: \n' , onehot)

Vocabulary: [array(['amazing', 'fun', 'is', 'nlp'], dtype=object)]
One Hot Encoding: 
 [[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
